In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
dataset = pd.read_csv('StudentsPerformance.csv')

In [4]:
dataset['average_score']=((dataset["math_score"]+dataset["reading_score"]+dataset["writing_score"])/3).round()
dataset['results'] = np.where(dataset['average_score']>= 50, '1', '0')
dataset.head()

,Unnamed: 0,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,average_score,results
0,1,female,group B,bachelor's degree,standard,none,72,72,74,73.0,1
1,2,female,group C,some college,standard,completed,69,90,88,82.0,1
2,3,female,group B,master's degree,standard,none,90,95,93,93.0,1
3,4,male,group A,associate's degree,free/reduced,none,47,57,44,49.0,0
4,5,male,group C,some college,standard,none,76,78,75,76.0,1

In [19]:
from sklearn.preprocessing import LabelEncoder
label_encoder= LabelEncoder()
dataset['gender'] = label_encoder.fit_transform(dataset['gender'])
dataset['race_ethnicity'] = label_encoder.fit_transform(dataset['race_ethnicity'])
dataset['parental_level_of_education'] = label_encoder.fit_transform(dataset['parental_level_of_education'])
dataset['lunch'] = label_encoder.fit_transform(dataset['lunch'])
dataset['test_preparation_course'] = label_encoder.fit_transform(dataset['test_preparation_course'])
dataset.head()

,Unnamed: 0,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,average_score,results
0,1,0,1,1,1,1,72,72,74,73.0,1
1,2,0,2,4,1,0,69,90,88,82.0,1
2,3,0,1,3,1,1,90,95,93,93.0,1
3,4,1,0,0,0,1,47,57,44,49.0,0
4,5,1,2,4,1,1,76,78,75,76.0,1

In [6]:
x = dataset.drop(['results'], axis=1)

y = dataset['results']

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [8]:
x_train.shape, x_test.shape

((750, 10), (250, 10))

In [9]:
from sklearn.svm import SVC

In [10]:
from sklearn.metrics import accuracy_score

In [11]:
svc=SVC()

In [12]:
svc.fit(x_train,y_train)

SVC()

In [13]:
y_pred=svc.predict(x_test)

In [14]:
print('Model accuracy score with default hyperparameters: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with default hyperparameters: 0.9120

In [15]:
svc=SVC(C=100.0)

In [16]:
svc.fit(x_train,y_train)

SVC(C=100.0)

In [17]:
y_pred=svc.predict(x_test)

In [18]:
print('Model accuracy score with radial basis functional kernel and C=100.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with radial basis functional kernel and C=100.0 : 0.9920